//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_HeadCountHR
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string ItemId_HR { get; set; }
        public string ItemId_DirectType { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string ItemId_JobFunction { get; set; }
        public string ItemId_Title { get; set; }
        public string AltwName { get; set; }
    }
}
