//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_Capex
    {
        public int Id { get; set; }
        public string ItemId_AssetExp { get; set; }
        public string ProjectName { get; set; }
        public string ProjectRemark { get; set; }
        public string ItemId_AssetExpType { get; set; }
        public string ItemId_Purpose { get; set; }
        public Nullable<int> SepLast { get; set; }
        public Nullable<int> OctLast { get; set; }
        public Nullable<int> NovLast { get; set; }
        public Nullable<int> DecLast { get; set; }
        public Nullable<int> Jan { get; set; }
        public Nullable<int> Feb { get; set; }
        public Nullable<int> Mar { get; set; }
        public Nullable<int> Apr { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> Jun { get; set; }
        public Nullable<int> Jul { get; set; }
        public Nullable<int> Aug { get; set; }
        public Nullable<int> Sep { get; set; }
        public Nullable<int> Oct { get; set; }
        public Nullable<int> Nov { get; set; }
        public Nullable<int> Dec { get; set; }
        public string Date { get; set; }
        public string DepartmentId { get; set; }
        public string Version { get; set; }
        public string Factory { get; set; }
        public Nullable<int> JulLast { get; set; }
        public Nullable<int> AugLast { get; set; }
        public string InternalOrder { get; set; }
        public Nullable<int> ProjectAmount { get; set; }
    }
}
