//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDIEntities : DbContext
    {
        public EDIEntities()
            : base("name=EDIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UploadLog> UploadLog { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<PosColumnMap> PosColumnMap { get; set; }
        public virtual DbSet<PosData> PosData { get; set; }
        public virtual DbSet<PosOrderMapping> PosOrderMapping { get; set; }
        public virtual DbSet<ReportFile> ReportFile { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Pos> Pos { get; set; }
        public virtual DbSet<ItemCatalog> ItemCatalog { get; set; }
        public virtual DbSet<Budget_Capex> Budget_Capex { get; set; }
        public virtual DbSet<Budget_HeadCount> Budget_HeadCount { get; set; }
        public virtual DbSet<Budget_Scrap> Budget_Scrap { get; set; }
        public virtual DbSet<Budget_DepartmentReport> Budget_DepartmentReport { get; set; }
        public virtual DbSet<Budget_FileVersionBudget> Budget_FileVersionBudget { get; set; }
        public virtual DbSet<Budget_DeptExpense> Budget_DeptExpense { get; set; }
        public virtual DbSet<Budget_DeptKPI> Budget_DeptKPI { get; set; }
        public virtual DbSet<Budget_Traveling> Budget_Traveling { get; set; }
        public virtual DbSet<Budget_Cost> Budget_Cost { get; set; }
        public virtual DbSet<Budget_CostTravelingMapping> Budget_CostTravelingMapping { get; set; }
        public virtual DbSet<Budget_LoginReviewCommonCost> Budget_LoginReviewCommonCost { get; set; }
        public virtual DbSet<Budget_LoginReviewReport> Budget_LoginReviewReport { get; set; }
        public virtual DbSet<Budget_LoginUploadCommonCost> Budget_LoginUploadCommonCost { get; set; }
        public virtual DbSet<Budget_LoginUploadReport> Budget_LoginUploadReport { get; set; }
        public virtual DbSet<Budget_HeadCountHR> Budget_HeadCountHR { get; set; }
        public virtual DbSet<SAP_PriceList> SAP_PriceList { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<Vote_ItemCatalog> Vote_ItemCatalog { get; set; }
        public virtual DbSet<Vote_Mapping> Vote_Mapping { get; set; }
        public virtual DbSet<ButtonLog> ButtonLog { get; set; }
        public virtual DbSet<Edi_Customer> Edi_Customer { get; set; }
        public virtual DbSet<Edi_SalesHeader> Edi_SalesHeader { get; set; }
        public virtual DbSet<Edi_SalesHeader_855> Edi_SalesHeader_855 { get; set; }
        public virtual DbSet<Edi_SalesItem> Edi_SalesItem { get; set; }
        public virtual DbSet<Edi_SalesItem_855> Edi_SalesItem_855 { get; set; }
        public virtual DbSet<Edi_SalesPartner> Edi_SalesPartner { get; set; }
        public virtual DbSet<Edi_SalesSchedule> Edi_SalesSchedule { get; set; }
        public virtual DbSet<Edi_SalesSchedule_855> Edi_SalesSchedule_855 { get; set; }
        public virtual DbSet<Edi_Pos> Edi_Pos { get; set; }
    }
}
