//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edi_SalesItem_855
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public string MATERIAL { get; set; }
        public string CUST_MAT35 { get; set; }
        public string ITM_NUMBER { get; set; }
        public string TARGET_QTY { get; set; }
        public string CustomerUnit { get; set; }
        public string Price { get; set; }
        public string CustomerItemNumber { get; set; }
        public string CustomerUnitOfPrice { get; set; }
        public string DateTime { get; set; }
    }
}
