//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edi_SalesPartner
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public string PARTN_ROLE { get; set; }
        public string PARTN_NUMB { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string REGION { get; set; }
        public string POSTL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string NAME { get; set; }
        public string TELEPHONE { get; set; }
        public string DateTime { get; set; }
    }
}
