//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edi_SalesHeader_855
    {
        public int Id { get; set; }
        public string PURCH_NO_C { get; set; }
        public string PURCH_DATE { get; set; }
        public string Status { get; set; }
        public string DateTime { get; set; }
        public string OrderNumber { get; set; }
    }
}
