//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pos
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Distributor { get; set; }
        public string Branch { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Series { get; set; }
        public string PartNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ResellingExt { get; set; }
        public string ACCT { get; set; }
        public string CustomerName { get; set; }
        public string MarketCode { get; set; }
        public string Market { get; set; }
        public string SubSegmentCode { get; set; }
        public string SubSegment { get; set; }
        public string Remarks { get; set; }
        public string CustomerPO { get; set; }
        public string ShipDate { get; set; }
        public string ShipDate2 { get; set; }
        public string ShipMonth { get; set; }
        public string ShipQuarter { get; set; }
        public string CountryCode { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public Nullable<int> FK_LoginId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Status { get; set; }
    }
}
