//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosOrderMapping
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Distributor { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> Address { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> ZIP { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> PartNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> InvoiceDate { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> ResellingExt { get; set; }
        public Nullable<int> ACCT { get; set; }
        public Nullable<int> CustomerName { get; set; }
        public Nullable<int> MarketCode { get; set; }
        public Nullable<int> Market { get; set; }
        public Nullable<int> SubSegmentCode { get; set; }
        public Nullable<int> SubSegment { get; set; }
        public Nullable<int> Remarks { get; set; }
        public Nullable<int> CustomerPO { get; set; }
        public Nullable<int> ShipDate { get; set; }
        public Nullable<int> ShipDate2 { get; set; }
        public Nullable<int> ShipMonth { get; set; }
        public Nullable<int> ShipQuarter { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> Model { get; set; }
        public int Start { get; set; }
        public string SplitChar { get; set; }
        public string ModelName { get; set; }
    }
}
