//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_PriceList
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string EndCustomerId { get; set; }
        public string EndCustomerName { get; set; }
        public string PartNumber { get; set; }
        public string Currency { get; set; }
        public Nullable<int> MOQ1 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<int> MOQ2 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<int> MOQ3 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<int> MOQ4 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<int> MOQ5 { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public Nullable<int> MOQ6 { get; set; }
        public Nullable<decimal> Price6 { get; set; }
        public Nullable<int> MOQ7 { get; set; }
        public Nullable<decimal> Price7 { get; set; }
        public Nullable<int> MOQ8 { get; set; }
        public Nullable<decimal> Price8 { get; set; }
        public Nullable<int> MOQ9 { get; set; }
        public Nullable<decimal> Price9 { get; set; }
        public Nullable<int> MOQ10 { get; set; }
        public Nullable<decimal> Price10 { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Per { get; set; }
        public string TaxType { get; set; }
        public Nullable<int> TaxRate { get; set; }
        public string EffectiveDate { get; set; }
        public Nullable<bool> InsertSapPrice { get; set; }
    }
}
