//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadLog
    {
        public int Id { get; set; }
        public int FK_LoginId { get; set; }
        public string FileName { get; set; }
        public string UpdateTime { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> Success { get; set; }
        public string ServerFileName { get; set; }
    }
}
